### PR TITLE
fix: added prettier config

### PR DESCRIPTION
**Pull request by kimberleejohnson**
I took a first pass at adding prettier to daily-demos, following the instructions in the [prettier docs](https://prettier.io/docs/en/install.html). 

I have a few questions/callouts: 
- I'm ignoring all things /react-demo for now. Is this okay? Or, once prettier is set up correctly for the global demos repository, should I go back and add a separate .prettierrc within all things react/? 
- Following the docs, I made both a .prettierrc and an empty .prettierrc.json. Do we actually need both? 
- How does the .prettierrc config look? I modeled it off what I could see in other repositories, though I had questions about the setup in the [React Native playground](https://github.com/daily-co/react-native-daily-js-playground/blob/main/DailyPlayground/.prettierrc.js). 
- Should we be exporting any configuration [for sharing](https://prettier.io/docs/en/configuration.html#sharing-configurations), or hold on that until we're entirely moved over? 
- More of a note: I saw some interesting notes about the `<input>` tags in `remote-monitoring-human.html` that we'll chat about later. 

Thank you for your 👀 !

### CODE REVIEW

**Comment by philmillman** [comment]
- maybe just get paul's sign off on the changes in relation to the react stuff because it's a high traffic post/demo so I just want to make sure the post and any other references get updated along with it 
- I don't think you need both
- I think we're good for now
- sounds good, happy to sync up today or tomorrow

**Review by philmillman — APPROVED** [review]

**Comment by kimberleejohnson** [comment]
Hi, @kompfner! Another demos related question for you: 

As I've set up this PR, the daily-demos .prettierignore ignores any `react-demo/` or `react-demo-electro` files. Is there anything special you'd like us to set up for the react-demo? Otherwise, maybe I can un-ignore them in the .prettierignore? Our configuration should be the default we use on all things Daily. If that default configuration does wind up changing the demo, I'll be sure to add it to my list to fix the posts about the demo with updated code. 

Please let me know your thoughts when you have a minute, and thank you!

**Comment by kompfner** [comment]
Just getting my bearings here, apologies for any dumb questions. We [already have a Prettier config in daily-demos](https://github.com/daily-co/daily-demos/blob/main/.prettierrc), and I don't see any changes to the config in this PR. Does this PR do the work of actually running Prettier on all files (which maybe we hadn't done before)?

**Comment by philmillman** [comment]
> Just getting my bearings here, apologies for any dumb questions. We [already have a Prettier config in daily-demos](https://github.com/daily-co/daily-demos/blob/main/.prettierrc), and I don't see any changes to the config in this PR. Does this PR do the work of actually running Prettier on all files (which maybe we hadn't done before)?

yes

**Comment by kompfner** [comment]
> > Just getting my bearings here, apologies for any dumb questions. We [already have a Prettier config in daily-demos](https://github.com/daily-co/daily-demos/blob/main/.prettierrc), and I don't see any changes to the config in this PR. Does this PR do the work of actually running Prettier on all files (which maybe we hadn't done before)?
> 
> yes

In which case, no need to exclude any React stuff in `.prettierignore`, it should've already been under the influence of the existing `.prettierrc`!

**Comment by kompfner** [comment]
In fact I'm not 100% clear on why we need an extensive `.prettierignore` here

> > > Just getting my bearings here, apologies for any dumb questions. We [already have a Prettier config in daily-demos](https://github.com/daily-co/daily-demos/blob/main/.prettierrc), and I don't see any changes to the config in this PR. Does this PR do the work of actually running Prettier on all files (which maybe we hadn't done before)?
> > 
> > 
> > yes
> 
> In which case, no need to exclude any React stuff in `.prettierignore`, it should've already been under the influence of the existing `.prettierrc`!

If you *are* seeing a bunch of changes when you run Prettier on the React stuff, then let's talk—maybe something's up with how things are configured.

**Comment by philmillman** [comment]
> If you are seeing a bunch of changes when you run Prettier on the React stuff, then let's talk—maybe something's up with how things are configured.

I think the config was added well after you published this demo. The thinking was we wanted to be intentional about changing the code since it's also in one of our most popular posts.

**Comment by kimberleejohnson** [comment]
Thanks for your reviews, @kompfner and @philmillman! 

I just removed all things react-demo/ from the .prettierignore, double-checked, and it seems like none of the React files were changed after all (I looked at the "Files Changed" list). 

I'll plan on merging this at the end of the day in case you want to take another look, but if I don't hear from you I'll assume things are all good. 

Thanks again!

**Pull request merged**
